name: 'Upload Thunderstore Package'
description: 'Formats and uploads a Thunderstore package'
inputs:
  path: 
    descritpion: 'Path to the files of the mod'
    required: true
  community:
    description: 'Thunderstore community to publish to'
    required: true
  namespace:
    description: 'Name of the team to publish the mod under'
    required: true
  name:
    description: 'Name of the package'
    required: true
  version:
    description: 'Package version to publish'
    required: true
  icon:
    description: 'URL of the mod icon'
    required: true
  readme:
    description: 'URL of the mod README'
    required: true
  description:
    description: 'Description of the mod'
    required: true
    default: 'Example mod description'
  token:
    description: 'Thunderstore API token'
    required: true
outputs:
  url:
    description: 'URL of uploaded mod'
runs:
  using: docker
  image: Dockerfile
