name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          namespace: GreenTF
          description: Test
          dev: true
          token: lmao
          name: test
          version: 0.1.0
          community: Northstar
