name: Test Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          namespace: GreenTF
          description: Test
          dev: true
          token: ${{ secrets.TS_KEY }}
          name: test
          version: ${{ github.run_id }}.${{ github.run_number }}.${{ github.run_attempt }}
          community: Northstar

  publish:
    needs: test
    if: github.event_name == "push"
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prelease: false
        


        
